#ifndef COMPONENT_INTERNAL_TEMPERATURE_SENSOR_H_
#define COMPONENT_INTERNAL_TEMPERATURE_SENSOR_H_

#ifndef COMPONENT_TYPES_INTERNAL_TEMPERATURE_SENSOR_H_
#define COMPONENT_TYPES_INTERNAL_TEMPERATURE_SENSOR_H_

#include <float.h>


#endif /* COMPONENT_TYPES_INTERNAL_TEMPERATURE_SENSOR_H_ */

void InternalTemperatureSensor_Run_Convert(float tp, float tc, float* temperature);

#endif /* COMPONENT_INTERNAL_TEMPERATURE_SENSOR_H_ */
