coverage:
  precision: 2
  round: down
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        require_ci_to_pass: yes
        threshold: 0.1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
