[tool.pyright]
exclude = [
    "dev_tools/",
    "tests/",
    "tools/",
    "venv/"
]

analyzeUnannotatedFunctions = false
reportUnknownParameterType = false
reportOptionalOperand = false
reportOperatorIssue = false
