name: Merge commits from `release` to `main`

on:
  push:
    branches:
      - release

jobs:
  merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Merge
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/release
        git push
